version: '3'
services:
  db:
    image: postgres
    container_name: postgres-customer-base
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer-base