version: '3'
services:
  db:
    image: postgres
    container_name: postgres-customer-base
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer-base
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  test-db:
    image: postgres
    container_name: e2e-test-db
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer-base
    volumes:
      - pg_data-e2e:/var/lib/postgresql/data
    networks:
      - app-network

  integration-db:
    image: postgres
    container_name: integration-test-db
    ports:
      - "5452:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer-base
    volumes:
      - pg_data-integration:/var/lib/postgresql/data
    networks:
      - app-network

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - app-network

volumes:
  pg_data:
  pg_data-integration:
  pg_data-e2e:
  jenkins_data:

networks:
  app-network: